language: ruby

before_install:
  - rvm get head
  - gem install bundler

script: "bundle exec rake test"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby
  - jruby-9.1.0.0
  - rbx
gemfile:
  - gemfiles/active_record_40.gemfile
  - gemfiles/active_record_41.gemfile
  - gemfiles/active_record_42.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby
    - rvm: jruby-9.1.0.0
  fast_finish: true
